### ISSUE TITLE
Possible to retrieve the image stream?

### ISSUE THREAD

**Issue by beniroquai** [quartiq/ai9#1]
Hey @quartiq @jordens , thanks a lot for publishing the sources! May I kindly ask you how you were able to get the commands to control the device? Also would it be possible to retreive the image streams of the device and/or control motors manually? I have decoded their app, but it's a lot of "garbage" which makes looking into that a little difficult. Thanks in advance!

**Comment by jordens** [comment]
Sniffing the comms between app and device is all I did. You'll need to work through the noise.

**Comment by beniroquai** [comment]
Ok. Thanks! Just one more question, the stream is transferred over HTTP not
bluetooth, right?

**Comment by jordens** [comment]
No idea, sorry. IIRC there was only Bluetooth.
